/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Label: typeof import('primevue/label')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    Select: typeof import('primevue/select')['default']
    Sidebar: typeof import('primevue/sidebar')['default']
    SidebarAside: typeof import('primevue/sidebaraside')['default']
    SidebarBackdrop: typeof import('primevue/sidebarbackdrop')['default']
    SidebarContent: typeof import('primevue/sidebarcontent')['default']
    SidebarGroup: typeof import('primevue/sidebargroup')['default']
    SidebarGroupAction: typeof import('primevue/sidebargroupaction')['default']
    SidebarGroupContent: typeof import('primevue/sidebargroupcontent')['default']
    SidebarGroupLabel: typeof import('primevue/sidebargrouplabel')['default']
    SidebarHeader: typeof import('primevue/sidebarheader')['default']
    SidebarLayout: typeof import('primevue/sidebarlayout')['default']
    SidebarMain: typeof import('primevue/sidebarmain')['default']
    SidebarMenu: typeof import('primevue/sidebarmenu')['default']
    SidebarMenuBadge: typeof import('primevue/sidebarmenubadge')['default']
    SidebarMenuButton: typeof import('primevue/sidebarmenubutton')['default']
    SidebarMenuItem: typeof import('primevue/sidebarmenuitem')['default']
    SidebarMenuSub: typeof import('primevue/sidebarmenusub')['default']
    SidebarMenuSubButton: typeof import('primevue/sidebarmenusubbutton')['default']
    SidebarMenuSubItem: typeof import('primevue/sidebarmenusubitem')['default']
    SidebarPanel: typeof import('primevue/sidebarpanel')['default']
    SidebarRail: typeof import('primevue/sidebarrail')['default']
    SidebarSpacer: typeof import('primevue/sidebarspacer')['default']
    SidebarTrigger: typeof import('primevue/sidebartrigger')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
