services:
    mailhog:
      restart: always
      build: ./docker-compose/mailhog
      ports:
        - '1025:1025'
        - '8025:8025'
      networks:
        - sas

networks:
    sas:
        driver: bridge
