; PHP settings

[php]

; Maximum allowed size for uploaded files.
upload_max_filesize = 1G

; Must be greater than or equal to upload_max_filesize
post_max_size = 1G

; Allowed memory size.
memory_limit = 1280M
